importation/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import home
from importation import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('sales/', include('sales_import.urls', namespace='sales')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales_import/urls.py
from django.urls import path

from sales_import.views import upload_file, report_all_sales

app_name = 'sales_import'

urlpatterns = [
    path('upload/', upload_file, name='upload'),
    path('sales_report/', report_all_sales, name='sales_report'),
]

core/models.py
from django.db import models

# Create your models here.

sales_import/models.py
from django.db import models


class Sale(models.Model):
    buyer = models.CharField('Comprador', max_length=256, blank=False, null=True)
    description = models.CharField('Descricao', max_length=256, blank=False, null=True)
    unit_price = models.DecimalField('Preço Unitário', decimal_places=2, blank=False, null=True, max_digits=9)
    amount = models.DecimalField('Quantidade', decimal_places=1, blank=False, null=True, max_digits=9)
    address = models.CharField('Endereço', max_length=256, blank=False, null=True)
    supplier = models.CharField('Fornecedor', max_length=256, blank=False, null=True)

    class Meta:
        db_table = 'sales'

sales_import/forms.py
import mimetypes

from django.forms import forms


class FileImportForm(forms.Form):
    file = forms.FileField(help_text='Only text file is accepted.', required=True)

    def clean_file(self):
        valid_content_types = ['text/plain']

        uploaded_file = self.cleaned_data['file']

        file_mime_type = mimetypes.guess_type(uploaded_file.name)[0]

        if file_mime_type not in valid_content_types:
            raise forms.ValidationError('Invalid file format!', code='invalid')

        return uploaded_file

core/views.py
from django.shortcuts import redirect


def home(request):
    return redirect('sales:upload')

sales_import/views.py
import os

import pandas as pd
from django.http import HttpResponse
from django.shortcuts import render

from importation import settings
from sales_import.forms import FileImportForm
from .models import Sale
from .utils import handle_uploaded_file


def upload_file(request):
    if request.method == "POST":
        form = FileImportForm(request.POST, request.FILES)
        if form.is_valid():
            file_uploaded = request.FILES['file']
            handle_uploaded_file(file_uploaded)
            text_file = f'{settings.MEDIA_ROOT}/{file_uploaded}'

            df = pd.read_table(text_file, sep='\t')

            sale_instance = [
                Sale(
                    buyer=row['Comprador'],
                    description=row['Descrição'],
                    unit_price=row['Preço Unitário'],
                    amount=row['Quantidade'],
                    address=row['Endereço'],
                    supplier=row['Fornecedor']
                ) for index, row in df.iterrows()
            ]
            Sale.objects.bulk_create(sale_instance)

            os.remove(text_file)

            total_sales = df['Preço Unitário'].sum()

            pd.set_option('colheader_justify', 'left')
            last_imported_sales = df.to_html(index=False, classes="table table-striped", border=None)

            return render(request, 'sales_import/list_imports.html',
                          {'last_imported_sales': last_imported_sales, 'total_sales': total_sales})
        else:
            return HttpResponse(request, form.errors)
    else:
        form = FileImportForm()
        return render(request, 'sales_import/upload.html', {'form': form})


def report_all_sales(request):
    sales_qs = Sale.objects.all().values('buyer', 'description', 'unit_price', 'amount', 'address', 'supplier')

    table_columns = ['Comprador', 'Descrição', 'Preço Unitário', 'Quantidade', 'Endereço', 'Fornecedor']
    pd.set_option('colheader_justify', 'left')
    df = pd.DataFrame.from_records(sales_qs)
    df.columns = table_columns

    total_sales = df['Preço Unitário'].sum()

    sales = df.to_html(index=False, classes="table table-striped", border=None)
    return render(request, 'sales_import/report_all_sales.html', {'sales': sales, 'total_sales': total_sales})

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>Import APP</title>
</head>
<body>

{% include "core/includes/menu.html" %}

<span style="padding: 1px;"></span>

<div class="container-fluid">
    {% block body %}
    {% endblock %}
</div>

</body>
</html>

core/templates/core/includes/menu.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Import APP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sales_import:upload' %}">Upload File</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sales_import:sales_report' %}">Sales Report</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

sales_import/templates/sales_import/list_imports.html
{% extends 'core/base.html' %}

{% block body %}

    <h2>Last Imported Sales</h2>

    <span style="padding: 1px;"></span>

    {{ last_imported_sales | safe }}

    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Total Sales: {{ total_sales }}</h5>
        </div>
    </div>

{% endblock %}

sales_import/templates/sales_import/report_all_sales.html
{% extends 'core/base.html' %}

{% block body %}

    <h2>Sales</h2>

    <span style="padding: 1px;"></span>

    {{ sales | safe }}

    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Total Sales: {{ total_sales }}</h5>
        </div>
    </div>

{% endblock %}

sales_import/templates/sales_import/upload.html
{% extends 'core/base.html' %}
{% block body %}

    <h2>Upload Text File</h2>

    <span style="padding: 1px;"></span>

    <form method="post" enctype="multipart/form-data">
        <div class="col-4 row">
            <div class="input-group mb-3">
                {% csrf_token %}
                <input class="form-control" type="file" name="file" required="True" id="id_file">
                <input type="submit" class="btn-check" id="btn-check-2-outlined" checked autocomplete="off">
                <label class="input-group-text" for="btn-check-2-outlined">Upload</label>
            </div>
        </div>
    </form>
{% endblock %}